<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tp3_openhours"
 *
 * Auto generated by Extension Builder 2018-04-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'tt_address OpenHours',
    'description' => 'Öffnungszeiten für tt_address &amp; businessview',
    'category' => 'misc',
    'author' => 'Thomas Ruta',
    'author_email' => 'email@thomasruta.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
